export default {
    "120": "데이터는 시각 인식으로 원본 표에서 추출되어 빠른 검색 참고용입니다. 정식 견적·설계 전 원본 표로 확인하십시오.",
    "119": "클릭하여 확대",
    "118": "회사 제품 카탈로그 전체 온라인 버전 — 페이지 넘기기, 확대, 장 이동 지원",
    "117": "전자 카탈로그",
    "116": "이 카테고리 데이터 추출 준비 중입니다",
    "115": "데이터는 시각 인식으로 원본 표에서 추출되어 빠른 검색 참고용입니다. 정식 견적·설계 전 원본 표로 확인하십시오.",
    "114": "원본 표 보기",
    "113": "임의 값으로 필터: 예. 2, Sch40, 150, 610",
    "112": "데이터 검색",
    "111": "규격 도면",
    "110": "Guided by integrity, surviving on quality and growing on reputation, we look forward to creating win-win partnerships and a brighter future with customers worldwide.",
    "109": "Sales have grown from the initial markets of Japan, South Korea, Singapore and India to over 30 countries and regions including the USA, Canada, Australia, Italy, Israel, Russia, Saudi Arabia, Turkmenistan, Egypt and South Africa.",
    "108": "Adhering to reputation first and customer foremost, we have built a stable supply base: 40+ fitting suppliers, plus partnerships with dozens of major mills — TPCO, CSST, Hengyang Valin, Tsingshan, Jianlong, Bao Steel, Baogang, Anshan, Tonggang, Yantai Steel Tube, Liaoyang, Wuxi Seamless, Chengde and more — including an equity relationship with Yantai Steel.",
    "107": "Pipes cover carbon steel, stainless steel and alloy steel, manufactured to ASTM, ASME, API 5L, API 5CT, DIN, EN and GOST standards.",
    "106": "As China's economy and steel industry expanded, the company gradually transformed from fittings-only trading to exporting a full range of steel pipes, meeting international demand for pipes and matching accessories.",
    "105": "Initially focused on exporting pipe fittings — carbon steel and stainless elbows, tees, reducers and caps to ASME B16.9, B16.28, JIS, DIN and GOST standards — along with flanges complying with ANSI, API, MSS, DIN, UNI, KS and JIS standards.",
    "104": "남아공",
    "103": "이집트",
    "102": "투르크메니스탄",
    "101": "사우디아라비아",
    "100": "러시아",
    "99": "이스라엘",
    "98": "이탈리아",
    "97": "호주",
    "96": "캐나다",
    "95": "미국",
    "94": "인도",
    "93": "싱가포르",
    "92": "한국",
    "91": "일본",
    "90": "랴오 ICP号 XXXXXXXX",
    "89": "입력이 너무 깁니다",
    "88": "문의 내용을 입력해 주세요",
    "87": "연락처를 입력해 주세요",
    "86": "이름을 입력해 주세요",
    "85": "전송 실패, 다시 시도해 주세요",
    "84": "문의가 접수되었습니다. 곧 연락드리겠습니다",
    "83": "문의 보내기",
    "82": "아래 정보를 입력해 주시면 빠르게 회신드리겠습니다",
    "81": "온라인 문의",
    "80": "팩스",
    "79": "휴대폰",
    "78": "전화",
    "77": "주소",
    "76": "성실을 바탕으로 고객과 함께 상생의 미래 창조",
    "75": "국제 표준을 엄격히 적용해 모든 배치가 고객 요구 충족",
    "74": "고객 최우선 — 공급자·고객과 장기 안정적 파트너십",
    "73": "신뢰로 발전",
    "72": "품질로 생존",
    "71": "신뢰 우선",
    "70": "경영 이념",
    "69": "수출 시장",
    "68": "협력 제철소",
    "67": "시장과 이념",
    "66": "공급 체계",
    "65": "사업 전환",
    "64": "회사 개요",
    "63": "30년간 배관 제품 수출에 집중, 전 세계 고객과 상생 실현",
    "62": "제품 사진",
    "61": "일치하는 규격표가 없습니다. 다른 키워드를 시도해 주세요",
    "60": "규격표 검색: 예. B16.9, A53, 두께, 엘보, 150#",
    "59": "표준",
    "58": "탄소강/스테인리스 플랜지, ANSI·API·MSS·DIN·UNI·KS·JIS 표준 지원",
    "57": "탄소강/스테인리스/합금 관부속: 엘보, 티, 크로스, 리듀서, 캡 등",
    "56": "구조용/유체수송/저중압 보일러/고압 보일러/원유 정제/비료설비/선박용 관, 오일 케이싱·튜빙",
    "55": "플랜지 제품",
    "54": "관 부속 제품",
    "53": "Starting from pipe fittings export, we have grown into a comprehensive exporter of steel pipes, fittings and flanges, with stable partnerships with dozens of major steel mills and 40+ fitting suppliers.",
    "52": "Dalian Pipe & Fitting Engineering Co., Ltd., formerly Xinyi'ou International Trade Co., Ltd., was founded in 1993 in Dalian, Liaoning — the largest port city in Northeast China. Leveraging Dalian's geographic advantages and the strong industrial base of the three northeastern provinces, the company has grown steadily over 30+ years.",
    "51": "ASME / ANSI / API / DIN / EN / JIS 국제 표준의 강관·관부속·플랜지 전문 수출업체",
    "50": "지금 문의하기",
    "49": "요구사항을 남겨주시면 빠르게 연락드리겠습니다",
    "48": "견적이나 기술 지원이 필요하신가요?",
    "47": "개 국가 및 지역",
    "46": "배관 부품 공급사",
    "45": "년 수출 경험",
    "44": "설립",
    "43": "제품 보기",
    "42": "30년 이상 배관·부속 수출 경험 · 30개국 이상 판매",
    "41": "프리미엄 품질이 안전을 만듭니다",
    "40": "더 보기",
    "39": "자세히 보기",
    "38": "연락처",
    "37": "빠른 링크",
    "36": "언어",
    "35": "제품",
    "1": "대련관화부품도관유한공사",
    "2": "첫 페이지",
    "3": "회사 소개",
    "4": "제품 전시",
    "5": "연락처",
    "6": "안전하고 내구성이 뛰어난 고급 품질",
    "7": "언어 수정 오류가 발견되었습니다. 페이지를 새로 고쳐서 읽으십시오!",
    "8": "제출",
    "9": "전화: +86 +411 6666 9976 / 6666 9971 / 666 9972",
    "10": "휴대폰: +86 180 4261 9992",
    "11": "팩스: +86 +411 6666 9975",
    "12": "호칭을 적어주세요. 오 ~",
    "13": "너무 길게 입력했어요.",
    "14": "연락처 적어주세요.",
    "15": "댓글 달아주세요. 오 ~",
    "16": "댓글이 제출되었습니다 ~",
    "17": "댓글이 실패했습니다. 다시 시도하십시오.",
    "18": "©2024 판권소유 대련관화부품도관유한회사",
    "19": "XXXXXXXXX 번호",
    "20": "게시판",
    "21": "명칭: 대련관화부품도관유한회사",
    "22": "주소: 중국·랴오닝성 다롄시 중산구 루쉰로 191호 환해아파트 1단원 3층 22호",
    "23": "당신의 호칭",
    "24": "연락처",
    "25": "메모할 내용",
    "26": "플랜지 제품군",
    "27": "매개변수 상세 정보 보기",
    "28": "강관 제품군",
    "29": "주요경영제품: 구조관/수송유체관/저중압보일러관/고압보일러관/석유분열관/화학비료설비용관/선박용관/오일튜브",
    "30": "강관 제품",
    "31": "파이프 제품군",
    "32": "대련관화부품도관유한회사의 전신은 신이유럽국제무역유한회사로서 1993년에 건설되기 시작하였고 동북 3성에서 가장 큰 항구도시인 료녕성 대련에 자리잡고있다.대련의 독특한 우월한 지리적조건에 근거하여 동북3성의 풍부한 공업기초는 우리 회사도 근 20년간의 경영을 거쳐 끊임없이 발전하고 강대해지고있다.당사는 건설 초기에 탄소강 스테인리스강 커브, 삼통, 이경관, 관모, 실행 가능한 표준 ASME B16.9, B16.28, JIS, DIN, GOST 등을 포함한 각종 파이프라인 부품을 수출하는 것을 위주로 경영하였다.플랜지에는 ANSI, API, MSS, DIN, UNI KS, JIS 등의 표준이 포함됩니다.제품의 응용 범위는 조선, 석유 화학 공업, 기계 제조, 건축, 송수, 송유 송기, 나아가 전력 우주 등 각 분야를 포함한다.중국의 경제 기초와 철강 산업이 끊임없이 강대해짐에 따라 우리 회사의 경영 방향도 단일 경영 부품에서 점차 각종 관재를 경영하고 수출하는 것으로 전환하여 국제 시장의 관재 및 그 부대적인 각종 부품에 대한 전면적인 수요에 영합한다.강관에는 탄소강, 스테인리스강, 합금강 등 재료가 포함되며 집행가능한 표준에는 ASTM, ASME, API5L, API5CT, DIN, EN GOST 등이 포함된다.근 20년간의 경영관리를 통해 당사는 신용제일고객지상의 원칙에 따라 안정적인 공급기지를 형성하고 설립하였으며 배관부품공급업체 40여개를 포함하고 강관합작기업으로는 TPCO, CSST, HENGYANG VALIN, TSINGSHAN STEEL, YANGZHOU, JIANLONG STEEL, BAO STEEL, BAOGANG STEEL, ANG STEEL, ANG STEL, ANG STEL, ANG STEL, ANG SAN SEEL, ANG SERGAIL, QUGSTANG SAONG SEEL, QUEL, QUGSTEEL SAONG SELIEL, QULSTEEL SAONG SAONG SAONG SEEL, QULSTEEL, QUEL SAONG SAONG SAONG 대형 탄소강, 스테인리스강, 무봉용접봉관 생산업체를 설립하고 그 중 YANTAISTEEL과 투자지분관계를 맺었다.제품 판매 범위도 초기의 일본, 한국, 싱가포르 인도에서 미국, 캐나다, 오스트레일리아, 이탈리아, 이스라엘, 러시아, 사우디아라비아, 투르크메니스탄, 이집트, 남아프리카 등 많은 국가 지역으로 발전했다.우리 회사는 신용을 근본으로 하는 원칙에 입각하여 품질로 생존을 추구하고 신용으로 발전하는 기업 경영 이념으로 더욱 만족스러운 제품과 서비스로 많은 고객과 함께 윈윈 국면을 개척하고 아름다운 미래를 함께 창조하고자 합니다.",
    "33": "주요 제품: 탄소강 플랜지 / 스테인리스강 플랜지 / 합금 플랜지",
    "34": "주요 제품: 탄소 강철 파이프 / 스테인리스 강철 파이프 / 합금 파이프"
}